/**
 * Export utilities for SupplyChainIQ analyses.
 *
 * Generates a clean Markdown report from an analysis dict and triggers
 * a browser download via Blob URL. No backend round-trip — the analysis
 * is already in memory on the client.
 */

const SEVERITY_EMOJI = {
  Critical: '🔴',
  High: '🟠',
  Medium: '🟡',
  Low: '🟢',
};

function fmtPct(n) {
  if (typeof n !== 'number') return '—';
  return `${Math.round(n * 100)}%`;
}

function safeArr(x) {
  return Array.isArray(x) ? x : [];
}

/**
 * Build a Markdown string from a SupplyChainIQ analysis.
 */
export function buildMarkdownReport(analysis, opts = {}) {
  if (!analysis) return '';

  const date = new Date().toISOString().slice(0, 10);
  const company = opts.companyName || 'Your Company';
  const lines = [];

  lines.push(`# SupplyChainIQ Risk Brief`);
  lines.push('');
  lines.push(`**Prepared for:** ${company}  `);
  lines.push(`**Date:** ${date}  `);
  if (analysis.overall_risk_level) {
    lines.push(`**Overall risk:** ${SEVERITY_EMOJI[analysis.overall_risk_level] || ''} ${analysis.overall_risk_level}  `);
  }
  if (analysis.provider_meta?.provider_used) {
    lines.push(
      `**AI engine:** ${analysis.provider_meta.provider_used}${
        analysis.provider_meta.is_mock ? ' (demo mode)' : ''
      }`
    );
  }
  lines.push('');

  if (analysis.summary) {
    lines.push(`## Executive summary`);
    lines.push('');
    lines.push(analysis.summary);
    lines.push('');
  }

  const riskNodes = safeArr(analysis.risk_nodes);
  if (riskNodes.length > 0) {
    lines.push(`## Risk nodes (${riskNodes.length})`);
    lines.push('');
    riskNodes.forEach((r, i) => {
      lines.push(`### ${i + 1}. ${SEVERITY_EMOJI[r.risk_level] || ''} ${r.node || 'Unnamed node'}`);
      lines.push('');
      lines.push(`- **Severity:** ${r.risk_level || 'Unknown'}`);
      lines.push(`- **Category:** ${r.category || 'general'}`);
      lines.push(`- **Confidence:** ${fmtPct(r.confidence_score)}`);
      lines.push('');
      if (r.cause) {
        lines.push(`**Cause.** ${r.cause}`);
        lines.push('');
      }
      const evidence = safeArr(r.evidence);
      if (evidence.length > 0) {
        lines.push(`**Grounded in:**`);
        evidence.forEach((e) => lines.push(`- ${e}`));
        lines.push('');
      }
      if (r.recommended_action) {
        lines.push(`**Recommended action.** ${r.recommended_action}`);
        lines.push('');
      }
    });
  }

  const graph = analysis.supply_chain_graph;
  if (graph && safeArr(graph.nodes).length > 0) {
    lines.push(`## Supply chain graph`);
    lines.push('');
    const byRole = {};
    graph.nodes.forEach((n) => {
      const r = n.role || 'other';
      if (!byRole[r]) byRole[r] = [];
      byRole[r].push(n);
    });
    ['supplier', 'factory', 'port', 'destination', 'other'].forEach((role) => {
      const list = byRole[role];
      if (!list || list.length === 0) return;
      const label = role.charAt(0).toUpperCase() + role.slice(1) + 's';
      lines.push(`**${label}:** ${list.map((n) => n.label + (n.location ? ` (${n.location})` : '')).join(', ')}`);
      lines.push('');
    });
  }

  const followups = safeArr(analysis.follow_up_suggestions);
  if (followups.length > 0) {
    lines.push(`## Suggested next questions`);
    lines.push('');
    followups.forEach((q) => lines.push(`- ${q}`));
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by SupplyChainIQ — AI-powered supply chain risk intelligence for SMEs.*`);

  return lines.join('\n');
}

/**
 * Download a string as a file via the browser.
 */
export function downloadTextFile(filename, content, mimeType = 'text/markdown') {
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  // Free the blob URL on the next tick so the click has time to fire
  setTimeout(() => URL.revokeObjectURL(url), 0);
}

/**
 * One-shot helper: build the markdown and trigger the download.
 */
export function exportAnalysisAsMarkdown(analysis, opts = {}) {
  const md = buildMarkdownReport(analysis, opts);
  const stamp = new Date().toISOString().slice(0, 10);
  const slug = (opts.companyName || 'supplychainiq').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  downloadTextFile(`${slug}-risk-brief-${stamp}.md`, md);
}

/* ============================================================ */
/*  HTML report — standalone, renders beautifully in any browser  */
/* ============================================================ */

const SEVERITY_HTML = {
  Critical: { color: '#dc2626', bg: '#fef2f2', border: '#fecaca' },
  High:     { color: '#ea580c', bg: '#fff7ed', border: '#fed7aa' },
  Medium:   { color: '#d97706', bg: '#fffbeb', border: '#fde68a' },
  Low:      { color: '#059669', bg: '#ecfdf5', border: '#a7f3d0' },
};

function escapeHtml(s) {
  if (s == null) return '';
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function sevBadge(level) {
  const s = SEVERITY_HTML[level] || SEVERITY_HTML.Medium;
  return `<span class="sev-badge" style="color:${s.color};background:${s.bg};border-color:${s.border};">${escapeHtml(level || 'Unknown')}</span>`;
}

/**
 * Build a standalone HTML string from a SupplyChainIQ analysis.
 * The output is a complete HTML document with inline CSS — no external
 * assets — so it renders identically when opened from disk, emailed,
 * or pasted into a wiki.
 */
export function buildHTMLReport(analysis, opts = {}) {
  if (!analysis) return '';
  const date = new Date().toISOString().slice(0, 10);
  const company = opts.companyName || 'Your Company';
  const overall = analysis.overall_risk_level;
  const overallSev = SEVERITY_HTML[overall] || SEVERITY_HTML.Medium;

  const riskNodes = safeArr(analysis.risk_nodes);
  const graph = analysis.supply_chain_graph;
  const followups = safeArr(analysis.follow_up_suggestions);

  const riskCardsHtml = riskNodes.map((r, i) => {
    const sev = SEVERITY_HTML[r.risk_level] || SEVERITY_HTML.Medium;
    const evidenceList = safeArr(r.evidence)
      .map((e) => `<li>${escapeHtml(e)}</li>`)
      .join('');
    const evidenceBlock = evidenceList
      ? `<div class="evidence"><div class="label">Grounded in</div><ul>${evidenceList}</ul></div>`
      : '';
    return `
      <section class="risk-card" style="border-left-color:${sev.color};">
        <header>
          <h3>${i + 1}. ${escapeHtml(r.node || 'Unnamed node')}</h3>
          ${sevBadge(r.risk_level)}
        </header>
        <div class="meta">
          <span><strong>Category:</strong> ${escapeHtml(r.category || 'general')}</span>
          <span><strong>Confidence:</strong> ${fmtPct(r.confidence_score)}</span>
        </div>
        ${r.cause ? `<p class="cause">${escapeHtml(r.cause)}</p>` : ''}
        ${evidenceBlock}
        ${r.recommended_action ? `<div class="action"><div class="label">Recommended action</div><p>${escapeHtml(r.recommended_action)}</p></div>` : ''}
      </section>`;
  }).join('');

  let graphBlock = '';
  if (graph && safeArr(graph.nodes).length > 0) {
    const byRole = {};
    graph.nodes.forEach((n) => {
      const r = n.role || 'other';
      if (!byRole[r]) byRole[r] = [];
      byRole[r].push(n);
    });
    const roleRows = ['supplier', 'factory', 'port', 'destination', 'other']
      .map((role) => {
        const list = byRole[role];
        if (!list || list.length === 0) return '';
        const label = role.charAt(0).toUpperCase() + role.slice(1) + 's';
        const chips = list
          .map((n) => `<span class="chip">${escapeHtml(n.label)}${n.location ? ` <em>(${escapeHtml(n.location)})</em>` : ''}</span>`)
          .join(' ');
        return `<div class="graph-row"><div class="graph-role">${label}</div><div class="graph-chips">${chips}</div></div>`;
      })
      .filter(Boolean)
      .join('');
    graphBlock = `
      <section class="graph">
        <h2>Supply chain graph</h2>
        ${roleRows}
      </section>`;
  }

  const followupsBlock = followups.length
    ? `<section class="followups"><h2>Suggested next questions</h2><ul>${followups.map((q) => `<li>${escapeHtml(q)}</li>`).join('')}</ul></section>`
    : '';

  const providerChip = analysis.provider_meta?.provider_used
    ? `<span class="provider">AI engine: <strong>${escapeHtml(analysis.provider_meta.provider_used)}</strong>${analysis.provider_meta.is_mock ? ' (demo mode)' : ''}</span>`
    : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>SupplyChainIQ Risk Brief — ${escapeHtml(company)}</title>
<style>
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
    background: #f8fafc;
    color: #0f172a;
    line-height: 1.55;
    padding: 40px 24px;
  }
  .container { max-width: 780px; margin: 0 auto; }
  header.top {
    border-bottom: 2px solid #e2e8f0;
    padding-bottom: 20px;
    margin-bottom: 28px;
  }
  header.top h1 {
    margin: 0 0 4px 0;
    font-size: 28px;
    font-weight: 700;
    letter-spacing: -0.01em;
  }
  header.top .brand { color: #2563eb; }
  header.top .meta-row {
    display: flex;
    flex-wrap: wrap;
    gap: 16px;
    margin-top: 12px;
    font-size: 13px;
    color: #64748b;
  }
  header.top .meta-row strong { color: #0f172a; }
  .overall-pill {
    display: inline-flex;
    align-items: center;
    gap: 10px;
    padding: 10px 16px;
    border-radius: 12px;
    border: 1px solid ${overallSev.border};
    background: ${overallSev.bg};
    color: ${overallSev.color};
    font-weight: 700;
    font-size: 14px;
    margin-top: 16px;
  }
  .overall-pill .label {
    font-size: 10px;
    text-transform: uppercase;
    letter-spacing: 0.12em;
    color: #64748b;
    font-weight: 600;
  }
  h2 {
    font-size: 16px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    color: #475569;
    margin: 32px 0 12px 0;
    padding-bottom: 6px;
    border-bottom: 1px solid #e2e8f0;
  }
  .summary { font-size: 15px; color: #334155; }
  .risk-card {
    border: 1px solid #e2e8f0;
    border-left: 4px solid #94a3b8;
    border-radius: 8px;
    padding: 16px 18px;
    margin-bottom: 14px;
    background: #ffffff;
  }
  .risk-card header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    gap: 12px;
    margin-bottom: 8px;
  }
  .risk-card h3 {
    margin: 0;
    font-size: 15px;
    font-weight: 700;
    color: #0f172a;
  }
  .sev-badge {
    display: inline-block;
    padding: 3px 8px;
    border-radius: 4px;
    border: 1px solid;
    font-size: 10px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    white-space: nowrap;
  }
  .risk-card .meta {
    display: flex;
    gap: 16px;
    font-size: 12px;
    color: #64748b;
    margin-bottom: 8px;
  }
  .risk-card .cause {
    font-size: 13px;
    color: #334155;
    margin: 8px 0 12px 0;
  }
  .evidence, .action {
    border-radius: 6px;
    padding: 10px 12px;
    margin-top: 10px;
  }
  .evidence { background: #f1f5f9; }
  .action { background: #eff6ff; border: 1px solid #dbeafe; }
  .evidence .label, .action .label {
    font-size: 9px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.12em;
    color: #64748b;
    margin-bottom: 4px;
  }
  .action .label { color: #2563eb; }
  .evidence ul { margin: 0; padding-left: 16px; font-size: 12px; color: #475569; }
  .evidence li { margin: 2px 0; }
  .action p { margin: 0; font-size: 13px; color: #1e293b; }
  .graph-row {
    display: flex;
    gap: 12px;
    margin-bottom: 8px;
    align-items: baseline;
  }
  .graph-role {
    font-size: 10px;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    color: #64748b;
    font-weight: 700;
    min-width: 110px;
  }
  .graph-chips { flex: 1; }
  .chip {
    display: inline-block;
    background: #ffffff;
    border: 1px solid #cbd5e1;
    border-radius: 20px;
    padding: 4px 10px;
    margin: 2px 4px 2px 0;
    font-size: 12px;
    color: #334155;
  }
  .chip em { color: #64748b; font-style: normal; }
  .followups ul { padding-left: 20px; font-size: 13px; color: #475569; }
  .followups li { margin: 4px 0; }
  footer {
    margin-top: 40px;
    padding-top: 20px;
    border-top: 1px solid #e2e8f0;
    font-size: 11px;
    color: #94a3b8;
    text-align: center;
  }
  .provider {
    display: inline-block;
    font-size: 11px;
    color: #64748b;
    background: #f1f5f9;
    padding: 4px 10px;
    border-radius: 4px;
    margin-top: 8px;
  }
  @media print {
    body { background: #ffffff; padding: 20px; }
    .risk-card { page-break-inside: avoid; }
  }
</style>
</head>
<body>
  <div class="container">
    <header class="top">
      <h1>SupplyChain<span class="brand">IQ</span> Risk Brief</h1>
      <div class="meta-row">
        <span><strong>Prepared for:</strong> ${escapeHtml(company)}</span>
        <span><strong>Date:</strong> ${date}</span>
      </div>
      ${overall ? `<div class="overall-pill"><span class="label">Overall risk</span><span>${escapeHtml(overall)}</span></div>` : ''}
      ${providerChip ? `<div>${providerChip}</div>` : ''}
    </header>

    ${analysis.summary ? `<section><h2>Executive summary</h2><p class="summary">${escapeHtml(analysis.summary)}</p></section>` : ''}

    ${riskNodes.length ? `<section><h2>Risk nodes (${riskNodes.length})</h2>${riskCardsHtml}</section>` : ''}

    ${graphBlock}

    ${followupsBlock}

    <footer>
      Generated by SupplyChainIQ — AI-powered supply chain risk intelligence for SMEs.
    </footer>
  </div>
</body>
</html>`;
}

/**
 * One-shot helper: build the HTML and trigger the download.
 */
export function exportAnalysisAsHTML(analysis, opts = {}) {
  const html = buildHTMLReport(analysis, opts);
  const stamp = new Date().toISOString().slice(0, 10);
  const slug = (opts.companyName || 'supplychainiq').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  downloadTextFile(`${slug}-risk-brief-${stamp}.html`, html, 'text/html');
}

/**
 * Open the HTML report in a new window and trigger the browser print dialog
 * with the page already styled for print. The user picks "Save as PDF" as
 * their destination — same approach Notion / Linear / GitHub use.
 *
 * Why not bundle jsPDF? It's 2MB+, the output looks worse than print-to-PDF,
 * and the browser already does this perfectly.
 */
export function exportAnalysisAsPDF(analysis, opts = {}) {
  const html = buildHTMLReport(analysis, opts);

  // Inject a print stylesheet + auto-trigger script before </head>
  const printAugmented = html.replace(
    '</head>',
    `<style>
      @media print {
        body { margin: 0; padding: 24px; }
        .no-print, button { display: none !important; }
        @page { size: A4; margin: 18mm 14mm; }
      }
    </style>
    <script>
      window.addEventListener('load', function () {
        // Small delay so fonts/layout settle before the print dialog opens
        setTimeout(function () { window.print(); }, 250);
      });
      // Auto-close the popup after the user finishes printing/saving
      window.addEventListener('afterprint', function () {
        setTimeout(function () { window.close(); }, 300);
      });
    </script>
    </head>`
  );

  const popup = window.open('', '_blank', 'width=900,height=1100');
  if (!popup) {
    // Popup blocked — fall back to downloading the HTML so the user can
    // open it themselves and print from there.
    // eslint-disable-next-line no-alert
    alert(
      'Popup blocked. Please allow popups for this site to export as PDF, ' +
      'or use the HTML export and print from your browser.'
    );
    return;
  }
  popup.document.open();
  popup.document.write(printAugmented);
  popup.document.close();
}
